# Uncomment this line to define a global platform for your project

platform :ios, '7.0'
inhibit_all_warnings!


target 'Donky Rich Message PopUp Demo' do

pod "Donky-RichMessage-PopUp"

end

target 'Donky Rich Message PopUp DemoTests' do

end

