# Uncomment this line to define a global platform for your project

platform :ios, '7.0'
inhibit_all_warnings!

target 'Donky Rich Message Logic Demo' do

pod "Donky-RichMessage-Logic"

end

target 'Donky Rich Message Logic DemoTests' do

end

