# Uncomment this line to define a global platform for your project

platform :ios, '7.0'
inhibit_all_warnings!

target 'Donky Simple Push UI Demo' do

pod "Donky-SimplePush-UI"

end

target 'Donky Simple Push UI DemoTests' do

end

